include:
    template: SAST.gitlab-ci.yml

stages:
  - test
  - package


image_build:
  image: docker:git
  stage: package
  only:
    - master
    - develop
    #- feature/fullcicd
  services:
    - docker:dind
  script:
    - cd ui/
    - ls
    - docker info
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker build -f Dockerfile-prod -t "${CI_REGISTRY_IMAGE}:latest" .
    - docker tag "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    - test ! -z "${CI_COMMIT_TAG}" && docker push "${CI_REGISTRY_IMAGE}:latest"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
