export const API_URL = process.env.REACT_APP_API_URL || '';
export const DYNAMODB_ACCESS_KEY_ID = process.env.REACT_APP_DYNAMODB_ACCESS_KEY_ID;
export const DYNAMODB_SECRET_ACCESS_KEY = process.env.REACT_APP_DYNAMODB_SECRET_ACCESS_KEY;
export const DYNAMODB_TABLE = process.env.REACT_APP_DYNAMODB_TABLE || 'atlas-staging';

export const COGNITO_SECRET = process.env.REACT_APP_COGNITO_SECRET;
export const COGNITO_DOMAIN = process.env.REACT_APP_COGNITO_DOMAIN;
export const COGNITO_CLIENT_ID = process.env.REACT_APP_COGNITO_CLIENT_ID;
export const COGNITO_CALLBACK_URL = process.env.REACT_APP_COGNITO_CALLBACK_URL;
export const COGNITO_USERINFO_ENDPOINT = process.env.REACT_APP_COGNITO_USERINFO_ENDPOINT;
export const COGNITO_TOKEN_ENDPOINT = process.env.REACT_APP_COGNITO_TOKEN_ENDPOINT;
