apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nmr_explore
  # Change this to the namespace the Prometheus instance is running in
  namespace: nmr_explore-monitoring
  labels:
    app: nmr_explore
    prometheus: kaleido-apl
spec:
  selector:
    matchLabels:
      app: nmr_explore
  namespaceSelector:
    matchNames:
    - nmr_explore
  endpoints:
  - port: http-metrics
    interval: 15s
