apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-ci
  namespace: __CI_PROJ_NAME__
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: __CI_PROJ_NAME__
  name: gitlab-ci
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-ci
  namespace: __CI_PROJ_NAME__
subjects:
- kind: ServiceAccount
  name: gitlab-ci
  namespace: __CI_PROJ_NAME__
roleRef:
  kind: Role
  name: gitlab-ci
  apiGroup: rbac.authorization.k8s.io
